[package]
name = "cfc-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Colony Firewall Control - iced GUI"

[[bin]]
name = "colony-firewall"
path = "src/main.rs"

[dependencies]
colony-ui = "0.1.4"
cfc-core = { path = "../cfc-core" }
cfc-proto = { path = "../cfc-proto" }
cfc-client = { path = "../cfc-client" }

iced = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
futures = { workspace = true }

serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
ipnet = { workspace = true }
